package com.moza.bankingApi.dto.response;

import com.moza.bankingApi.model.enums.Role;
import lombok.Data;

/**
 * {@code UserResponse} is a Data Transfer Object (DTO) used to encapsulate
 * user information that is safe and appropriate to return in API responses.
 *
 * <p>This class excludes sensitive data such as passwords, and typically
 * represents a view of the user entity after creation, authentication,
 * or in administrative listings.</p>
 *
 * @author Miro Pedro T. Lino
 */
@Data
public class UserResponse {

    /**
     * The unique identifier of the user.
     * <p>Typically generated by the database upon creation.</p>
     */
    private Long id;

    /**
     * The username of the user.
     * <p>This value is unique and serves as the login credential.</p>
     */
    private String username;

    /**
     * The role assigned to the user, such as ADMIN or CLIENTE.
     * <p>Defined by the {@link Role} enum.</p>
     */
    private Role role;
}
